--Returns all client information related to applications for a specifed period
with parameters as (
	select	date_trunc('month', CURRENT_DATE)::date AS "StartDate"
    	,	  (date_trunc('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::date AS "EndDate"
    	,   (date_trunc('month', CURRENT_DATE) - INTERVAL '7 days')::date AS "SevenDaysPriorStart"
    	,   (date_trunc('month', CURRENT_DATE) - INTERVAL '1 days')::date AS "SevenDaysPriorEnd"
),
Data as  (
            select  c."ClientId" 
            , c."UserId" 
            , c."PersonId" 
            , c."Title" 
            , c."Firstname" 
            , c."Surname" 
            , c."IDNumber" 
            , c."DateOfBirth" 
            , c."Gender" 
            , c."MaritalStatusId"
            , c."MaritalAgreement"
            , c."EthnicityId"
            , c."OTPVerified"
            , c."NewStatusId"
            , c."CountryOfBirthId"
            , c."LanguageId"
            , c."ModifiedBy" 
            , c."ModifiedDate" 
            , c."BranchId"
            , c."PropertyOwnershipId"
            , c."Updated" 
            , c."CompanyId" 
            , c."ChannelCode" 
            , c."IsDelinquent" 
            , c."IsDebtReview"
            , c."DeliquencyReasonId"
      from 	  backoffice.sqlmig."Application" a, backoffice.sqlmig."Client" c, parameters p
      where   a."CreateDate" between p."SevenDaysPriorStart" and p."EndDate"
      and     a."ClientId" = c."ClientId"
      union all
      select  c."ClientId" 
            , c."UserId" 
            , c."PersonId" 
            , c."Title" 
            , c."Firstname" 
            , c."Surname" 
            , c."IDNumber" 
            , c."DateOfBirth" 
            , c."Gender" 
            , c."MaritalStatusId"
            , c."MaritalAgreement"
            , c."EthnicityId"
            , c."OTPVerified"
            , c."NewStatusId"
            , c."CountryOfBirthId"
            , c."LanguageId"
            , c."ModifiedBy" 
            , c."ModifiedDate" 
            , c."BranchId"
            , c."PropertyOwnershipId"
            , c."Updated" 
            , c."CompanyId" 
            , c."ChannelCode" 
            , c."IsDelinquent" 
            , c."IsDebtReview"
            , c."DeliquencyReasonId"
      from    backoffice.public."ACC_Account" ac , backoffice.sqlmig."Client" c , parameters p
      where   ac."LoanType" = 'L'
      and     (  		ac."CloseDate" is null
					or 	ac."CloseDate" between p."SevenDaysPriorStart" and p."EndDate"
					or  ac."StatusChangeDate" between p."SevenDaysPriorStart" and p."EndDate" 
			)
      and     ac."ClientId" = c."ClientId"
) 
Select distinct * from data;
