drop MATERIALIZED VIEW "Cumulative_Bad_Rates_MV";
CREATE MATERIALIZED VIEW "Cumulative_Bad_Rates_MV"	AS 
SELECT 	"OpenMonth" 
    ,		"Loan_Term" 
    ,		"Loan_Size" 
    ,		"MonthsOnBook" 
    ,   "PaymentFrequency" 
		,		"Debtors_Bank" 
		,   "ROLLd_Loan" 
		,   "Product" 
		,		"ClientCategory" 
		,   "ServiceProvider" 
		, 	"CDE_Override" 
		,		"BureauScoreBand"
		,   "Bureau" 	
		,   "OverDue_Segment"
    ,		sum(1) AS "Total_Accounts"
    ,		sum("Vintage_Indicator") AS "Total_Accounts_InArrears" 		
FROM 		"Account_Vintage_Indicators"
GROUP BY 	"OpenMonth"
    ,		"Loan_Term" 
    ,		"Loan_Size" 
    ,		"MonthsOnBook" 
    ,   "PaymentFrequency" 
		,		"Debtors_Bank" 
		,   "ROLLd_Loan" 
		,   "Product" 
		,		"ClientCategory" 
		,   "ServiceProvider" 
		, 	"CDE_Override" 
		,		"BureauScoreBand"
		,   "Bureau" 	
		,   "OverDue_Segment";

-- View indexes:
CREATE UNIQUE INDEX cumulative_bad_rates_mv_uq ON "Cumulative_Bad_Rates_MV" USING btree (
        "OpenMonth" 
    ,		"Loan_Term" 
    ,		"Loan_Size" 
    ,		"MonthsOnBook" 
    ,   "PaymentFrequency" 
		,		"Debtors_Bank" 
		,   "ROLLd_Loan" 
		,   "Product" 
		,		"ClientCategory" 
		,   "ServiceProvider" 
		, 	"CDE_Override" 
		,		"BureauScoreBand"
		,   "Bureau" 	
		,   "OverDue_Segment");